module.exports = {
    //auth
    LOGIN: 'lOGIN',
    LOGOUT: 'LOGOUT',
    LOADING_UI: 'LOADING_UI',
    UNLOADING_UI: 'UNLOADING_UI',
    SET_ERRORS: 'SET_ERRORS',
    UNSET_ERRORS: 'UNSET_ERRORS',
    SET_MOBILE_MENU: 'SET_MOBILE_MENU',
    TOGGLE_MENU: 'TOGGLE_MENU',

    //filers
    ADD_FILTER: 'ADD_FILTER',
    SET_START_DATE: 'SET_START_DATE',
    SET_END_DATE: 'SET_END_DATE',
    SORT_BY_LIKES: 'SORT_BY_LIKES',
    SORT_BY_DATE: 'SORT_BY_DATE',

    GET_GRIEVANCES: 'GET_GRIEVANCES',
    GET_SELECTED: 'GET_SELECTED',
    SELECT_GRIEVANCE: 'SELECT_GRIEVANCE',
    DESELECT_GRIEVANCE: 'DESELECT_GRIEVANCE',
    ALLOCATE_DATE: 'ALLOCATE_DATE',

};