module.exports = {
    //auth
    LOGIN: 'lOGIN',
    LOGOUT: 'LOGOUT',
    LOADING_UI: 'LOADING_UI',
    UNLOADING_UI: 'UNLOADING_UI',
    SET_ERRORS: 'SET_ERRORS',
    UNSET_ERRORS: 'UNSET_ERRORS',
    SET_MOBILE_MENU: 'SET_MOBILE_MENU',
    TOGGLE_MENU: 'TOGGLE_MENU',
    SET_USER_TYPE: 'SET_USER_TYPE',
    SET_USER: 'SET_USER',
    SET_COLLAPSED: 'SET_COLLAPSED',
    REJECT_GRIEVANCE: 'REJECT_GRIEVANCE',

    //filers
    SET_START_DATE: 'SET_START_DATE',
    ADD_FILTER: 'ADD_FILTER',
    SET_END_DATE: 'SET_END_DATE',
    SORT_BY_PENDING: 'SORT_BY_PENDING',
    SORT_BY_DATE: 'SORT_BY_DATE',

    GET_GRIEVANCES: 'GET_GRIEVANCES',
    GET_SELECTED: 'GET_SELECTED',
    SELECT_GRIEVANCE: 'SELECT_GRIEVANCE',
    DESELECT_GRIEVANCE: 'DESELECT_GRIEVANCE',
    ALLOCATE_DATE: 'ALLOCATE_DATE',
    GET_COMMITTEES: 'GET_COMMITTEES'
};